apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .secret-file: Y29ubmVjdGlvblN0cmluZz0nbW9uZ29kYitzcnY6Ly9Db250cmlidXRvcnM6a2owekwxUkZ4Q3VyTXNtMEBjbHVzdGVyMC5tenZ3bGd0Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMCc=
