---
name: CareDocs application
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    name: Build and Push CareDocs App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for Frontend
        run: npm install
        working-directory: frontend

      - name: Build Docker image for Frontend
        run: docker build -t -t vaibhavrawat/caredocs-frontend:build-${GITHUB_RUN_NUMBER} .
        working-directory: frontend

      - name: Push Docker image for Frontend
        run: docker push vaibhavrawat/caredocs-frontend:build-${GITHUB_RUN_NUMBER}

      # Build and push backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for Backend
        run: npm install
        working-directory: backend

      - name: Inject env for connection
        run: |
          echo 'connectionString="mongodb+srv://Contributors:kj0zL1RFxCurMsm0@cluster0.mzvwlgt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"' > backend/.env

      - name: Build Docker image for Backend
        run: docker build -t vaibhavrawat/caredocs-backend:latest .
        working-directory: backend

      - name: Push Docker image for Backend
        run: docker push vaibhavrawat/caredocs-backend:latest
